apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
spec:
  replicas: {{ .Values.client.replicas }}
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - name: client
        image: {{ .Values.client.image }}:{{ .Values.client.tag }}
        ports:
        - containerPort: {{ .Values.client.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: client-service
spec:
  selector:
    app: client
  ports:
  - port: {{ .Values.client.port }}
    targetPort: {{ .Values.client.port }}
    nodePort: 30000
  type: {{ .Values.service.type }}